version: '2'
services:
  watchdog:
    container_name: watchdog
    restart: always
    build:
      context: ./
      dockerfile: dockerfile

    environment:
      - MQTT_TOPIC_PUBLISHED=signal/EOL_test_result
      - BROKER_HOST=twn-pdb.sram.com

    stdin_open: true
    tty: true

    network_mode: "host"

    volumes:
      - /home/sram-prod/test_results:/eol_test_results
